# Generated by Django 5.2.17 on 2026-09-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="columns",
            field=models.JSONField(default=list),
        ),
    ]
