# Generated by Django 5.2.17 on 2026-09-19 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_importbatch_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="target_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.program",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="target_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.source",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="target_source_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
