# Generated by Django 5.2.17 on 2026-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceprofile",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="workspaceprofile",
            name="service_area_codes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
